### ISSUE TITLE
Errors due to deprecated versions and some other syntax errors

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Hostelite#1]
Sir, there are too much error and the app is not running as it is using many deprecated versions. kindly assign this issue to me @RitwikSingh28 
<img width="910" alt="Screenshot 2023-10-07 182153" src="https://github.com/HackSlashNITP/Hostelite/assets/125534462/54773d8f-b30c-4a77-864a-a33fb38e4f83">

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
Okay, I am assigning this issue to you. 

**Deadline**: 10 October, 10 PM :clock1: 

**Note:**
> - In the PR description, do remember to include the list showcasing the `dependency` changes and mention the errors that you resolved.
> - Include screenshots of the running application as proof that the errors have been fixed
