### ISSUE TITLE
UI enhancement of edit profile page

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Hostelite#3]
Sir, the UI of edit profile page of the application is not as per the design file. The Ui is not looking good. @RitwikSingh28 kindly assign this issue to me so that I can improve the UI as per the design file 
![WhatsApp Image 2023-10-12 at 00 13 16_2b939f3c](https://github.com/HackSlashNITP/Hostelite/assets/125534462/bb833dea-b2fc-41bc-8c6a-e7ba02674e48)

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
Assigning this issue to you. 

**Deadline:** :hourglass: August 14, 2023; 10:00 PM

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir the changes have been made. Kindly review them.
The UI is in accordance with the design file provided.
![WhatsApp Image 2023-10-15 at 11 49 02_aefe734c](https://github.com/HackSlashNITP/Hostelite/assets/125534462/7b85bbea-6053-4b33-8618-aa37a0b3bfd0)
