### ISSUE TITLE
UI enhancement of Mark Exit page

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Hostelite#4]
Sir, the UI of Mark Exit page in the hostelite page is not up to mark. The input text areas are not correctly aligned and the overall UI looks messed up. @RitwikSingh28 Sir kindly assign this issue to me so that I can improve it as per the design file.
![WhatsApp Image 2023-10-12 at 00 28 24_2290b8f5](https://github.com/HackSlashNITP/Hostelite/assets/125534462/c6f51ce8-515c-4be2-9326-9b8ad592684a)

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
Assigned it to you. How many days would you require to get this issue resolved?

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 I will complete the changes by tomorrow
