### ISSUE TITLE
Adding app icon to hostelite 

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Hostelite#5]
@RitwikSingh28 Sir, Currently there is not icon for hostelite app and the default is flutter icon. 
I want to update the icon of the application. Kindly assign this issue to me 
<img width="215" alt="Screenshot 2023-10-13 112105" src="https://github.com/HackSlashNITP/Hostelite/assets/125534462/69028c30-8ac9-4696-b61f-09733d325f7f">

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 

Please get it done by today, i.e. 14 October 2023, 22:00 IST

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Thank you sir. It will be completed before deadline

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
The PR hasn't been raised to target this issue. Kindly update me on the status of your work in resolving this issue

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir the previous PR wasn't merged, that's why I didn't raise it. 
I will raise the PR before 4 PM

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir I have updated the changes and PR has been raised. Kindly review the changes
